// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAARlXM0-_zr0fnDhqYOcCD3AdgGyonWno',
    appId: '1:447116138743:android:7fb1c821cefdb5a44d5bf2',
    messagingSenderId: '447116138743',
    projectId: 'bearscout-2046',
    storageBucket: 'bearscout-2046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvcnK93-rl9m7iFV8_xjAS9vo-PNhGtr0',
    appId: '1:447116138743:ios:39c0fafb05c362784d5bf2',
    messagingSenderId: '447116138743',
    projectId: 'bearscout-2046',
    storageBucket: 'bearscout-2046.firebasestorage.app',
    iosBundleId: 'org.tahomarobotics.scouting.bearscout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvcnK93-rl9m7iFV8_xjAS9vo-PNhGtr0',
    appId: '1:447116138743:ios:39c0fafb05c362784d5bf2',
    messagingSenderId: '447116138743',
    projectId: 'bearscout-2046',
    storageBucket: 'bearscout-2046.firebasestorage.app',
    iosBundleId: 'org.tahomarobotics.scouting.bearscout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8M_7BFjBHJZcDgLMxNwHCpkqPEx45gwY',
    appId: '1:447116138743:web:fb6b9548f8a84e214d5bf2',
    messagingSenderId: '447116138743',
    projectId: 'bearscout-2046',
    authDomain: 'bearscout-2046.firebaseapp.com',
    storageBucket: 'bearscout-2046.firebasestorage.app',
    measurementId: 'G-JPKC6T3LX5',
  );

}