name: Create GitHub Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract changelog section
        id: extract_changelog
        run: |
          TAG="${GITHUB_REF_NAME}"
          # extract lines after "## vX.Y.Z" up to next "## " header
          sed -n "/^## ${TAG}\$/,/^## /{/^## ${TAG}\$/d;/^## /d;p}" CHANGELOG.md > release_notes.md
          if [ ! -s release_notes.md ]; then
            echo "No changelog section for ${TAG}" >&2
            exit 1
          fi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          body_path: release_notes.md
          draft: false
          prerelease: false
