name: Build Windows Binary

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  version:
    uses: ./.github/workflows/version.yml

  build:
    needs: version
    runs-on: windows-latest
    env:
      FLUTTER_CHANNEL: stable
      APP_VERSION: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
      - name: Install dependencies
        run: flutter pub get
      - name: Build Windows app
        run: flutter build windows --release
      - name: Create artifacts directory
        run: mkdir -p artifacts
      - name: Create installer with Inno Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: windows/inno_setup.iss
          options: /DMyAppVersion=${{ env.APP_VERSION }} /O+
      - name: Copy installer to artifacts
        run: |
          Copy-Item -Path build\inno_setup\beariscope-installer.exe -Destination artifacts\beariscope-windows-${{ env.APP_VERSION }}-x86-64.exe
      - name: Zip Windows build
        run: |
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath artifacts\beariscope-windows-${{ env.APP_VERSION }}.zip
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: artifacts/*
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/beariscope-windows-${{ env.APP_VERSION }}-x86-64.exe
          name: Beariscope ${{ env.APP_VERSION }}
          generate_release_notes: true
